### ISSUE TITLE
Value of type 'SAMTextView' has no member 'addTarget'

### ISSUE THREAD

**Issue by luisfuertes** [soffes/SAMTextView#35]
Im trying to set the target "textViewDidChange" but

> Value of type 'SAMTextView' has no member 'addTarget'

My code
`self.tvComment.addTarget(self, action: "textFieldDidChange:", forControlEvents: UIControlEvents.EditingChanged)`

How can i do this?

**Comment by soffes** [comment]
It does. It's just a UITextView subclass. Check the documentation for UIControl.
